apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: account-reader
  namespace: aws-account-operator
rules:
  - apiGroups:
      - aws.managed.openshift.io
    resources:
      - accounts
    verbs:
      - '*'