apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-accounts
  namespace: aws-account-operator
subjects:
- kind: ServiceAccount
  name: aws-account-shredder
  namespace: aws-account-shredder
roleRef:
  kind: Role
  name: account-reader
  apiGroup: rbac.authorization.k8s.io