apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: aws-account-shredder
  name: aws-account-shredder
rules:
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - services
  - secrets
  verbs:
  - '*'